name: qabot-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - langchain==0.2.11
      - langchain-community==0.2.10
      - langchain-ibm==0.1.11
      - ibm-watsonx-ai==1.1.2
      - chromadb==0.4.24
      - pypdf==4.3.1
      - pydantic==2.9.1
      - gradio==4.44.0